const P = {
  ink: "#2a2547",
  dk: "#1a1730",
  blue: "#60a5fa",
  bluL: "#bcd9ff",
  gold: "#f5b942",
  goldD: "#c8881a",
  red: "#ef4444",
  grn: "#34d399",
  pur: "#a855f7",
  purD: "#7e22ce",
  wht: "#ECEAFF",
  sky: "#9fc7ff",
  rose: "#f0a6c0",
  roseD: "#c95f86",
  paper: "#e9e2cf",
  cream: "#fbf6e8",
};

interface SpriteData {
  px: number;
  palette: Record<string, string>;
  art: string[];
}

export const SPRITES: Record<string, SpriteData> = {
  controller: {
    px: 7,
    palette: { B: P.ink, b: "#3a3464", D: "#13101f", a: P.blue, x: P.red, y: P.gold, g: P.grn },
    art: [
      "................",
      "....BBBBBBBB....",
      "..BBbbbbbbbbBB..",
      ".BbbbbbbbbbbbbB.",
      ".BbDbbbbbbbbxbB.",
      "BbbDDDbbbbbyxgbB",
      "BbbbDbbbbbbbgbbB",
      "BbbbbbbbbbbbbbbB",
      ".BBbbbbbbbbbbBB.",
      "...BB......BB...",
    ],
  },
  camera: {
    px: 6,
    palette: { B: "#3a3464", L: P.blue, l: P.bluL, F: P.gold, w: P.wht },
    art: [
      "....BBB......",
      ".BBBBBBBBBBB.",
      ".BBBBBBBBBBF.",
      ".BBBLLLLLBBB.",
      ".BBLLlllLLBB.",
      ".BLLlwllllLB.",
      ".BLLllllllLB.",
      ".BBLLlllLLBB.",
      ".BBBLLLLLBBB.",
      ".BBBBBBBBBBB.",
    ],
  },
  shirt: {
    px: 6,
    palette: { G: P.pur, g: P.purD, c: P.wht },
    art: [
      "..GG.....GG..",
      ".GGGG...GGGG.",
      "GGGGGGcGGGGGG",
      "GGGGGcccGGGGG",
      "gGGGGGGGGGGGg",
      ".GGGGGGGGGGG.",
      "..GGGGGGGGG..",
      "..GGGGGGGGG..",
      "..GGGGGGGGG..",
      "..GGGGGGGGG..",
    ],
  },
  book: {
    px: 6,
    palette: { C: P.grn, s: "#0f7a52", p: P.cream, m: P.gold },
    art: [
      "............",
      ".CCCCCCCCCC.",
      ".CssCpppppm.",
      ".CssCppppppp",
      ".CssCpppppp.",
      ".CssCmmmppp.",
      ".CssCpppppp.",
      ".CssCpppppp.",
      ".CssCppppppp",
      ".CssCpppppm.",
      ".CCCCCCCCCC.",
      "............",
    ],
  },
  disk: {
    px: 6,
    palette: { B: P.blue, d: "#1a1730", m: P.bluL, w: P.wht },
    art: [
      "BBBBBBBBBBBB",
      "BdddddddddmB",
      "BdwwwwwwwdmB",
      "BdwwwwwwwdmB",
      "BdddddddddmB",
      "BBBBBBBBBBBB",
      "BmmmmmmmmmmB",
      "BmBBBBBBBmmB",
      "BmBdddddBmmB",
      "BmBdddddBmmB",
      "BmBdddddBmmB",
      "BBBBBBBBBBBB",
    ],
  },
  star: {
    px: 5,
    palette: { y: P.gold, o: P.goldD },
    art: [
      ".....y.....",
      ".....y.....",
      "....yyy....",
      "yyyyyyyyyyy",
      ".yyyyyyyyy.",
      "..yyyyyyy..",
      "..yyyoyyy..",
      ".yyyo.oyyy.",
      ".yyo...oyy.",
    ],
  },
  heart: {
    px: 5,
    palette: { r: P.red, d: "#b91c1c", w: "#ffb4b4" },
    art: [
      ".rr...rr.",
      "rrrr.rrrr",
      "rwrrrrrrr",
      "rwrrrrrrr",
      ".rrrrrrr.",
      "..rrrrr..",
      "...rrr...",
      "....r....",
    ],
  },
  coin: {
    px: 5,
    palette: { y: P.gold, o: P.goldD, w: "#fff0c2" },
    art: [
      "..ooo..",
      ".oyyyo.",
      "oyywyyo",
      "oyywyyo",
      "oyywyyo",
      ".oyyyo.",
      "..ooo..",
    ],
  },
  bolt: {
    px: 5,
    palette: { y: P.gold },
    art: ["...yy", "..yy.", ".yyyy", "..yy.", ".yy..", "yy..."],
  },
  github: {
    px: 5,
    palette: { w: "currentColor" },
    art: [
      "..wwwwww..",
      ".wwwwwwww.",
      "ww.ww.www.",
      "wwwwwwwwww",
      "wwwwwwwwww",
      "wwwwwwwwww",
      ".w.wwww.w.",
      ".w.ww.w.w.",
    ],
  },
  mail: {
    px: 5,
    palette: { w: "currentColor", d: "transparent" },
    art: [
      "wwwwwwwwww",
      "wwwwwwwwww",
      "wddwwwwddw",
      "wdddwwdddw",
      "wddddddddw",
      "wdddwwdddw",
      "wddwwwwddw",
      "wwwwwwwwww",
    ],
  },
  linkedin: {
    px: 5,
    palette: { w: "currentColor", d: "transparent" },
    art: [
      "wwwwwwwww",
      "wwwddwwww",
      "wwwddwwww",
      "wddwwddww",
      "wddwwddww",
      "wddwddddw",
      "wddwddddw",
      "wwwwwwwww",
    ],
  },
  download: {
    px: 5,
    palette: { w: "currentColor", d: "transparent" },
    art: [
      "dddwwddd",
      "dddwwddd",
      "dddwwddd",
      "dwwwwwwd",
      "ddwwwwdd",
      "dddwwddd",
      "dddddddd",
      "wwwwwwww",
    ],
  },
  terminal: {
    px: 5,
    palette: { w: "currentColor", d: "transparent" },
    art: [
      "wwwwwwwwww",
      "wddddddddw",
      "wdwddddddw",
      "wddwddddw.",
      "wdwddddddw",
      "wddddwwddw",
      "wddddddddw",
      "wwwwwwwwww",
    ],
  },
  arrowR: {
    px: 5,
    palette: { w: "currentColor" },
    art: [
      "....w...",
      "....ww..",
      "wwwwwww.",
      "wwwwwwww",
      "wwwwwww.",
      "....ww..",
      "....w...",
    ],
  },
  guitar: {
    px: 5,
    palette: { B: P.ink, G: P.gold, g: P.goldD, h: P.dk },
    art: [
      "...BBBB...",   // headstock
      "...BGGB...",
      "..BBGGBB..",   // tuning pegs
      "....BB....",   // neck
      "....BB....",
      "....BB....",
      "..BBBBB...",   // upper bout
      ".BGGGGGgB.",
      ".BGGhGGgB.",   // sound hole
      "..BBBBB...",   // waist
      ".BGGGGGGgB",   // lower bout
      "BGGGGGGGgB",
      "BGGGGGGGgB",
      ".BBBBBBBB.",
    ],
  },
  laptop: {
    px: 5,
    palette: { B: P.ink, s: "#0f2744", L: P.blue, l: P.bluL, b: "#3a3464", k: "#4d4880" },
    art: [
      ".BBBBBBBBBB.",
      "BssssssssssB",
      "BslLsssssssB",
      "BssssssssssB",
      "BssssssssssB",
      ".BBBBBBBBBB.",
      "bbbbbbbbbbbb",
      "bkkkbkkkbkkb",
      "bkkkkkkkkkkb",
      "bbbbbbbbbbbb",
    ],
  },
  power: {
    px: 5,
    palette: { w: "currentColor", d: "transparent" },
    art: [
      "...ww...",
      ".w.ww.w.",
      "ww.ww.ww",
      "ww.ww.ww",
      "ww....ww",
      ".ww..ww.",
      "..wwww..",
    ],
  },
  apple: {
    px: 5,
    palette: { R: P.red, r: "#b91c1c", h: "#ffb4b4", s: P.goldD, G: P.grn },
    art: [
      ".....s......",
      "...GGGss....",
      "..RRRRRRRR..",
      ".RRRRRRRRRR.",
      "RRhRRRRRRRRr",
      "RhhRRRRRRRRr",
      "RhRRRRRRRRrr",
      "RRRRRRRRRRrr",
      ".RRRRRRRRRr.",
      ".RRRRRRRRRr.",
      "..RRRR.RRR..",
      "...RR...RR..",
    ],
  },
  commonplace: {
    px: 5,
    palette: { B: P.ink, w: "#dbeafe", m: P.blue },
    art: [
      "BBBBBBBBBBBB",
      "BwwwwwwwwwwB",
      "BwmmmmwwwwwB",
      "BwwwwwwwwwwB",
      "BwmmmmmmmwwB",
      "BwwwwwwwwwwB",
      "BwmmmmwwwwwB",
      "BBBBBBBBBBBB",
      "..BB........",
      "...B........",
    ],
  },
};
